// Code generated by mockery v2.42.2. DO NOT EDIT.

package serviceMocks

import (
	context "context"

	"github.com/EmirShimshir/marketplace-core/domain"
	mock "github.com/stretchr/testify/mock"

	"github.com/EmirShimshir/marketplace-core/port"
)

// CartService is an autogenerated mock type for the ICartService type
type CartService struct {
	mock.Mock
}

// ClearCart provides a mock function with given fields: ctx, cartID
func (_m *CartService) ClearCart(ctx context.Context, cartID domain.ID) error {
	ret := _m.Called(ctx, cartID)

	if len(ret) == 0 {
		panic("no return value specified for ClearCart")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID) error); ok {
		r0 = rf(ctx, cartID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateCartItem provides a mock function with given fields: ctx, param
func (_m *CartService) CreateCartItem(ctx context.Context, param port.CreateCartItemParam) (domain.CartItem, error) {
	ret := _m.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for CreateCartItem")
	}

	var r0 domain.CartItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.CreateCartItemParam) (domain.CartItem, error)); ok {
		return rf(ctx, param)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.CreateCartItemParam) domain.CartItem); ok {
		r0 = rf(ctx, param)
	} else {
		r0 = ret.Get(0).(domain.CartItem)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.CreateCartItemParam) error); ok {
		r1 = rf(ctx, param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCartItem provides a mock function with given fields: ctx, CartItemID
func (_m *CartService) DeleteCartItem(ctx context.Context, CartItemID domain.ID) error {
	ret := _m.Called(ctx, CartItemID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCartItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID) error); ok {
		r0 = rf(ctx, CartItemID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCartByID provides a mock function with given fields: ctx, cartID
func (_m *CartService) GetCartByID(ctx context.Context, cartID domain.ID) (domain.Cart, error) {
	ret := _m.Called(ctx, cartID)

	if len(ret) == 0 {
		panic("no return value specified for GetCartByID")
	}

	var r0 domain.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID) (domain.Cart, error)); ok {
		return rf(ctx, cartID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID) domain.Cart); ok {
		r0 = rf(ctx, cartID)
	} else {
		r0 = ret.Get(0).(domain.Cart)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ID) error); ok {
		r1 = rf(ctx, cartID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCartItemByID provides a mock function with given fields: ctx, cartItemID
func (_m *CartService) GetCartItemByID(ctx context.Context, cartItemID domain.ID) (domain.CartItem, error) {
	ret := _m.Called(ctx, cartItemID)

	if len(ret) == 0 {
		panic("no return value specified for GetCartItemByID")
	}

	var r0 domain.CartItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID) (domain.CartItem, error)); ok {
		return rf(ctx, cartItemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID) domain.CartItem); ok {
		r0 = rf(ctx, cartItemID)
	} else {
		r0 = ret.Get(0).(domain.CartItem)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ID) error); ok {
		r1 = rf(ctx, cartItemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCartItem provides a mock function with given fields: ctx, cartItemID, param
func (_m *CartService) UpdateCartItem(ctx context.Context, cartItemID domain.ID, param port.UpdateCartItemParam) (domain.CartItem, error) {
	ret := _m.Called(ctx, cartItemID, param)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCartItem")
	}

	var r0 domain.CartItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID, port.UpdateCartItemParam) (domain.CartItem, error)); ok {
		return rf(ctx, cartItemID, param)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID, port.UpdateCartItemParam) domain.CartItem); ok {
		r0 = rf(ctx, cartItemID, param)
	} else {
		r0 = ret.Get(0).(domain.CartItem)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ID, port.UpdateCartItemParam) error); ok {
		r1 = rf(ctx, cartItemID, param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCartService creates a new instance of CartService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCartService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CartService {
	mock := &CartService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
